sudo: required
language: python
python:
  - "3.5"
  - "3.6"
addons:
  apt:
    packages:
    - gcc
    - g++
# command to install dependencies
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq gcc-4.8
  - export CC="gcc-4.8"
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install coverage
  - conda install numpy
  - conda install numba
  - conda install scipy
  - conda install pandas
  - conda install cython
  - conda install scikit-learn
  - pip install cvxopt
  - pip install cvxpy
  - pip install simpleutils
  - pip install coveralls
script:
  - export NUMBA_DISABLE_JIT=1
  - python setup.py build_ext --line_trace --inplace
  - coverage run --rcfile=./.coveragerc alphamind/tests/test_suite.py
  - coverage report --rcfile=./.coveragerc -i
  - coverage html --rcfile=./.coveragerc -i
after_success:
  - coveralls
