language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
sudo: false
addons:
  apt:
    source:
      - ubuntu-toolchain-r-test
    packages:
      - libblas-dev
      - liblapack-dev
      - gfortran
      - g++-4.8
      - gcc-4.8
env:
  - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"
before_install:
  - eval "${MATRIX_EVAL}"
install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install coverage
  - conda install numpy
  - conda install numba
  - conda install scipy
  - conda install pandas
  - conda install scikit-learn
  - conda install cython
  - pip install cvxopt
  - pip install cvxpy
  - pip install simpleutils
  - pip install coveralls
script:
  - export NUMBA_DISABLE_JIT=1
  - export LD_LIBRARY_PATH="$PWD/libs/lib/linux:$LD_LIBRARY_PATH"
  - python setup.py build_ext --inplace
  - coverage run alphamind/tests/test_suite.py
  - coverage report
  - coverage html
after_success:
  - coveralls
